#!/usr/bin/env python3
"""Emit the Persian morphology tables as a JavaScript data module.

``docs/assets/js/persian-stem.js`` mirrors the algorithm of
``scripts/persian_text.py`` — but it must never mirror the *data*. The affix
tables, verb paradigms, broken plurals, stopwords and exception lists are
exported from Python, so there is exactly one source of truth. CI fails if the
generated file drifts (``git diff --exit-code docs/assets/js/persian-stem-data.js``).

The lexicon is deliberately NOT in this file: it is dataset-dependent and
already ships inside ``docs/data/api/search-index.json``.

Usage:
    python scripts/generate_stem_data.py [--out PATH]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import persian_text as pt
from build_pages import ROOT

DEFAULT_OUT = ROOT / "docs" / "assets" / "js" / "persian-stem-data.js"

HEADER = """/* Generated by scripts/generate_stem_data.py from scripts/persian_text.py.
 * DO NOT EDIT BY HAND — CI fails when this file drifts from the Python source.
 *
 * Persian morphology tables shared by the browser stemmer
 * (docs/assets/js/persian-stem.js) and the build-time stemmer.
 */
"""


def payload() -> dict:
    return {
        "algorithm": "persian-root-v1",
        "zwnj": pt.ZWNJ,
        "minStemLength": pt.MIN_STEM_LENGTH,
        "minPartLength": pt.MIN_PART_LENGTH,
        "minRootLength": pt.MIN_ROOT_LENGTH,
        "maxCollapsedLength": pt.MAX_COLLAPSED_LENGTH,
        "safeSuffixes": list(pt.SAFE_SUFFIXES),
        "guardedSuffixes": list(pt.GUARDED_SUFFIXES),
        "prefixes": list(pt.PREFIXES),
        "stopwords": sorted(pt.STOPWORDS),
        "stemExceptions": sorted(pt.STEM_EXCEPTIONS),
        "brokenPlurals": dict(sorted(pt.BROKEN_PLURALS.items())),
        "verbStems": {k: list(v) for k, v in sorted(pt.VERB_STEMS.items())},
        "verbEndings": list(pt.VERB_ENDINGS),
        "noSplit": sorted(pt.NO_SPLIT),
        "confusables": [list(pair) for pair in pt.CONFUSABLES],
        # Character map: everything normalize() translates away. Emitted as an
        # object (not a Python str.maketrans table) so JS can use it directly.
        "charMap": dict(sorted(pt.CHAR_MAP.items())),
        "digitClasses": [pt.ARABIC_DIGITS, pt.PERSIAN_DIGITS],
    }


def render() -> str:
    data = json.dumps(payload(), ensure_ascii=False, indent=2, sort_keys=False)
    body = (
        HEADER
        + "(function (root, factory) {\n"
        + '  "use strict";\n'
        + "  var data = factory();\n"
        + '  if (typeof module !== "undefined" && module.exports) { module.exports = data; }\n'
        + '  if (root) { root.PERSIAN_STEM_DATA = data; }\n'
        + "})(typeof window !== \"undefined\" ? window : (typeof globalThis !== \"undefined\" ? globalThis : this), function () {\n"
        + '  "use strict";\n'
        + "  return "
        + data
        + ";\n});\n"
    )
    return body


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DEFAULT_OUT))
    args = parser.parse_args()
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(), encoding="utf-8")
    print(f"✅ persian-stem-data.js written ({out.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    main()
